// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkafkjvifovqyfbuglnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYWZranZpZm92cXlmYnVnbG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODcxNzYsImV4cCI6MjA2NzA2MzE3Nn0.xoWes0IvgOzZIGtPPGyvBHsegR1eOOqQlx_fRYD3UKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});